# syntax=docker/dockerfile:1


# Build stage

FROM node:20 as build

ENV NODE_ENV=production
WORKDIR /home/node/derzis/worker

COPY --chown=node:node ["package.json", "yarn.lock", ".yarnrc.yml", "../common/"]
COPY --chown=node:node [".yarn",  "../common/.yarn/"]
RUN cd ../common && yarn install --frozen-lockfile

USER 1000
CMD ["bin/worker.js"]

