#!/bin/bash

# create named pipe if it doesn't exist
if [[ ! -f live.log ]]; then
  mkfifo manager.live.log
fi

zstd --adapt --flush-interval=1 <live.log >>manager.log.zst &

unbuffer npm run dev 2>&1 | tee manager.live.log
