name: Node.js CI

on:
  push:
    branches: ['**'] # Runs on every branch push
  pull_request:

defaults:
  run:
    working-directory: './manager'
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [22.x, 23.x]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install manager dependencies
        run: npm install
      - name: Building manager
        run: npm run build
      - name: Testing manager
        run: npm test
